// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// USANDO SUPABASE EXTERNO wtrefsziscauokudnxgz (Aplicativo Bancodedados)
// Sobrescreve o .env gerenciado pelo Lovable Cloud para apontar ao banco migrado.
const SUPABASE_URL = "https://wtrefsziscauokudnxgz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_DLAlIkksoQ-2qO40Y0hfzA_0pazWsNk";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
